type: x-custom
describedBy: 
  headers: 
    Authorization: 
      description: |
        Used to send a valid OAuth 2 access token. The token must be preceeded by the word "Bearer".
      example: Bearer _token_
