delete?: 
  responses: 
    204: 
post?: 
  responses: 
    201: 
    400: 
get?: 
  responses: 
    200: 
head?: 
  responses: 
    200: 
patch?: 
  responses: 
    400: 
securedBy: [ oauth_2_0 , tokenSchema ]
type: generalResponseCodes
