get?: 
  responses: 
    200?: 
    201?: 
    204?: 
    300?: 
    304?: 
    400?: 
    401?: 
    403?: 
    404?: 
    405?: 
    415?: 
    500?: 
head?: 
  responses: 
    200?: 
    201?: 
    204?: 
    300?: 
    304?: 
    400?: 
    401?: 
    403?: 
    404?: 
    405?: 
    415?: 
    500?: 
post?: 
  responses: 
    200?: 
    201?: 
    204?: 
    300?: 
    304?: 
    400?: 
    401?: 
    403?: 
    404?: 
    405?: 
    415?: 
    500?: 
put?: 
  responses: 
    200?: 
    201?: 
    204?: 
    300?: 
    304?: 
    400?: 
    401?: 
    403?: 
    404?: 
    405?: 
    415?: 
    500?: 
delete?: 
  responses: 
    200?: 
    201?: 
    204?: 
    300?: 
    304?: 
    400?: 
    401?: 
    403?: 
    404?: 
    405?: 
    415?: 
    500?: 
patch?: 
  responses: 
    200?: 
    201?: 
    204?: 
    300?: 
    304?: 
    400?: 
    401?: 
    403?: 
    404?: 
    405?: 
    415?: 
    500?: 
