type: generalResource
description: Set, reset, or get information about a user password. This resource is available in REST API version 24.0 and later.
get: 
  description: Retreive password expiration status.
  responses: 
    200: 
      body: 
        application/xml: 
          schema: passwordExpiration-xml
          example: !include ../examples/passwordExpiration-xml-example.xml
        application/json: 
          schema: passwordExpiration
          example: !include ../examples/passwordExpiration-example.json
post: 
  description: Set the password.
  body: 
    application/xml: 
    application/json: 
      schema: passwordNew
      example: !include ../examples/passwordNew-example.json
delete: 
  description: Reset the password.
  responses: 
    200: 
      body: 
        application/xml: 
          schema: passwordReset-xml
          example: !include ../examples/passwordReset-xml-example.xml
        application/json: 
          schema: passwordReset
          example: !include ../examples/passwordReset-example.json
head: 
