queryParameters: 
  start: 
    description: "Starting date/time (Coordinated Universal Time (UTC)-not local- timezone) of the timespan for which to retrieve the data. The API ignores the seconds portion of the specified dateTime value (for example, 12:30:15 is interpreted as 12:30:00 UTC). The date and time should be provided in ISO 8601 format: YYYY-MM-DDThh:mm:ss+hh:mm. The date/time value for 'start' must chronologically precede 'end'."
    required: true
  end: 
    description: "Ending date/time (Coordinated Universal Time (UTC)-not local- timezone) of the timespan for which to retrieve the data. The API ignores the seconds portion of the specified dateTime value (for example, 12:35:15 is interpreted as 12:35:00 UTC). The date and time should be provided in ISO 8601 format: YYYY-MM-DDThh:mm:ss+hh:mm."
    required: true
